global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: skind
    metrics_path: /metrics
    static_configs:
      - targets:
        - skind:4643

  - job_name: processd
    metrics_path: /metrics
    static_configs:
      - targets:
        - processd:8080
